name: '(Issues Disabled)Mark and close stale pull requests'

on:
  # schedule:
  #   - cron: '0 0 * * *' # Runs daily at midnight

  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
            pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          # Only enable PR processing
          days-before-stale: 100
          days-before-close: 50
          stale-pr-message: 'This pull request is stale because it has been open for 30 days with no activity. Remove the stale label or comment or this will be closed in 7 days.'
          close-pr-message: 'This pull request was closed due to inactivity.'
          
          # Disable issues processing!
          stale-issue-message: ''
          close-issue-message: ''
          days-before-stale-issue: -1
          days-before-close-issue: -1
