name: "Create Dummy Cache Every 3 Minutes"

on:
  # schedule:
  #   - cron: '*/3 * * * *'  # Every 3 minutes
  workflow_dispatch:       # Allows manual runs too

jobs:
  create-cache:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p dummy-path && echo "hello" > dummy-path/file.txt
      - uses: actions/cache@v4
        with:
          path: dummy-path
          key: dummy-cache-${{ github.run_id }}-${{ github.run_number }}
