name: Repro stale - state_reason permissions

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/stale
        uses: actions/stale@v10.1.1
        with:
          # stale-issue-message: 'This issue is stale because it has been open for 50 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open for 50 days with no activity.'
          # days-before-issue-stale: 50
          days-before-pr-stale: 50
          days-before-pr-close: 1
  
          # close-issue-reason: 'completed'
          close-pr-message: 'Testing the closing of the pull request.'
          close-pr-reason: 'completed'
  
          # Helpful debug signal
          debug-only: false
