name: 'Testing 1184 Issue PR Branch'

on:
  workflow_dispatch: # Allows manual triggering
permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@enhancement/ignore-stale-labeling-events
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 300 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open for 300 days with no activity.'
          days-before-issue-stale: 300
          days-before-pr-stale: 300
          days-before-close: 100
          remove-stale-when-updated: 'true'
