name: Stale
on:
  # schedule:
  #   - cron: '40 3,4,5,6,7 * * *'
  workflow_dispatch: {}
jobs:
  stale:
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
      with:
        operations-per-run: 150
        days-before-stale: 173
        days-before-close: 7
        ascending: true
        stale-issue-message: '...'
        close-issue-message: '...'
        stale-pr-message: '...'
        close-pr-message: '...'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'no-stale'
        exempt-pr-labels: 'no-stale'
        remove-stale-when-updated: true
        delete-branch: true
        enable-statistics: true
