name: "1311 - Mark stale issues and pull requests "
on:
  workflow_dispatch: 
permissions:
  issues: write
  pull-requests: write
  actions: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: shamoon/stale@ignore-stale-label-events
        with:
          stale-issue-message: 'This issue is stale because it has been open for 150 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open for 150 days with no activity.'
          days-before-stale: 150
          days-before-close: 7
